### ISSUE TITLE
check-updates-rpm fails to detect updates depending on system state and TERM environment

### ISSUE THREAD

**Issue by barneydesmond** [anchor/tingle#2]
We've observed that `tingle check` will occasionally return a false negative, indicating that there are no pending updates, when in fact there are plenty. We eventually nailed this down to yum outputting Bold terminal codes, which breaks the awk regex in `check-updates-rpm`.

yum outputs bold text when the updated packages have already been downloaded but not installed, assuming that coloured output is enabled by default. This will occur if you `check` after a `warm`, or if the process is halted before/during the `apply` phase; rare but not implausible.

There are a few solutions to this that we can see:

1. Invoke as `TERM=dumb tingle check`
2. Modify the regex in `check-updates-rpm` to accept and ignore terminal control codes
3. Modify `check-updates-rpm` to invoke yum with `--color=never`
4. Modify `bigpty` to pass a suitable environment to `subprocess.call`, which would potentially affect/break/fix any other scripts that make use of `bigpty`

It's noted that this issue only affects interactive use. We've been using `at` to schedule our tingle runs and they work just fine because jobs appear to be run with `TERM=dumb`.

We have no particular preference for how/where the fix is made.

**Comment by lachlancooper** [comment]
I can confirm this behaviour myself, as I just spent a bit of time tracking down the same issue and went to report it before noticing this one. Thanks for the detailed report!

I'll see what I can do about getting it fixed.

**Comment by saj** [comment]
It has gotten to the point where I can no longer ignore this bug, so I'll take on this release. :)

**Comment by saj** [comment]
A new source release has been [cut](https://github.com/anchor/tingle/releases/tag/v0.5.5).

Tested on ELs 5, 6, and 7.

Thank you, Barney, for the bug report.
